### ISSUE TITLE
Login details for elm-authors on npm

### ISSUE THREAD

**Issue by naazy** [OxfordAbstracts/elm-authors#18]
@Conorc1000 I was unable to publish a new version of elm-authors to npm because I don't know the npm login details. Pretty please could you add it to our doc so we can publish? Thanks

**Comment by Conorc1000** [comment]
@naazy I have updated the NPM login details

**Comment by naazy** [comment]
Thanks @Conorc1000 :heart: I will publish to npm after you've reviewed https://github.com/OxfordAbstracts/elm-authors/pull/16
